name: 'Publish API Studio file changes to IDIG'
description: 'Publishes and updates API Studio Projects in IDIG'
inputs:
  idig_host:
    description: 'Domain name of the API Connect IDIG instance where API Studio files will be published and deleted.'
    required: true
  platform_idig_prefix:
    description: 'Platform IDIG Prefix'
    required: false
  changed_files:
    description: 'Files changed between current and previous commit'
    required: false
  deleted_files_content:
    description: 'Deleted files and their content from previous commit.'
    required: false
  insecure_skip_tls_verify:
    description: 'Insecure Skip TLS verify to allow self signed certificates'
    required: false
  auth_username:
    description: 'Authentication username'
    required: false
  auth_password:
    description: 'Authentication password'
    required: false

outputs:
  action-result:
    description: 'Result of the operation to publish API Studio project file changes to IDIG'
runs:
  using: 'node24'
  main: 'dist/index.js'